"""initial

Revision ID: 44dfe4213d01
Revises: 
Create Date: 2023-02-18 23:50:18.323077

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '44dfe4213d01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation',
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='operationstatusenum'), nullable=True),
    sa.Column('input_ref', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('uid', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_operation_created'), 'operation', ['created'], unique=False)
    op.create_index(op.f('ix_operation_input_ref'), 'operation', ['input_ref'], unique=False)
    op.create_index(op.f('ix_operation_uid'), 'operation', ['uid'], unique=False)
    op.create_table('performance',
    sa.Column('review_time', sa.Integer(), nullable=False),
    sa.Column('merge_time', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('team', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('uid', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_performance_date'), 'performance', ['date'], unique=False)
    op.create_index(op.f('ix_performance_merge_time'), 'performance', ['merge_time'], unique=False)
    op.create_index(op.f('ix_performance_review_time'), 'performance', ['review_time'], unique=False)
    op.create_index(op.f('ix_performance_team'), 'performance', ['team'], unique=False)
    op.create_index(op.f('ix_performance_uid'), 'performance', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_performance_uid'), table_name='performance')
    # op.drop_index(op.f('ix_performance_team'), table_name='performance')
    # op.drop_index(op.f('ix_performance_review_time'), table_name='performance')
    # op.drop_index(op.f('ix_performance_merge_time'), table_name='performance')
    # op.drop_index(op.f('ix_performance_date'), table_name='performance')
    op.drop_table('performance')
    op.drop_index(op.f('ix_operation_uid'), table_name='operation')
    op.drop_index(op.f('ix_operation_input_ref'), table_name='operation')
    op.drop_index(op.f('ix_operation_created'), table_name='operation')
    op.drop_table('operation')
    op.execute("""DROP TYPE operationstatusenum""")
    # ### end Alembic commands ###